### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by debpedrano** [Shouheng88/TranslateMyApp#2]
I would love to participate in making the project logo, I am willing to work on it Mr. @Shouheng88 .

**Comment by Shouheng88** [comment]
I'm glad to hear that :)
But I'm busy learning developing skills these days, so I couldn't put forward any good idea about the logo. You can design as you prefer :)

**Comment by debpedrano** [comment]
okay, I will just submit my design here. if you like it, I will make a PR. is that good ?

**Comment by Shouheng88** [comment]
OK

**Comment by debpedrano** [comment]
how about this one ? @Shouheng88  
![image](https://user-images.githubusercontent.com/40510200/43880797-746ace54-9bdc-11e8-9068-af93b03a6fec.png)

**Comment by Shouheng88** [comment]
Why should we use the background of a ear phone?

**Comment by debpedrano** [comment]
@Shouheng88 just to be classic I think, it is commonly used by the translators.

**Comment by debpedrano** [comment]
Hello, can I update the issue? please response. Thank you :) @Shouheng88
